### ISSUE TITLE
Security Data Issues - Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [transferwise/tw-tasks-executor#91]
Hi ,

url : https://github.com/transferwise/tw-tasks-executor/blob/0b1603f95e61de7f4c96eae88d33dea0717db29d/demoapp/src/main/resources/application.yml

![image](https://user-images.githubusercontent.com/46863888/104658290-255af580-56cb-11eb-8b8a-f0591c463d14.png)

have commit that need to remove from the github history
attacker can see it and use it ...

encrypt your secrets !!!!

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕

**Comment by yevhenii0** [comment]
Hey, thanks for a report! Fortunately that was a temporary instance created for testing purposes! Anyway the rds profile is indeed odd, removed it here 👉 https://github.com/transferwise/tw-tasks-executor/pull/92
