### ISSUE TITLE
How to setup development environment?

### ISSUE THREAD

**Issue by kumar-asista** [transferwise/tw-tasks-executor#96]
FAILURE: Build failed with an exception.

* Where:
Build file '/.../tw-tasks-executor/build.gradle' line: 16

* What went wrong:
Plugin [id: 'com.github.spotbugs', version: '4.6.0', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.spotbugs:com.github.spotbugs.gradle.plugin:4.6.0')
  Searched in the following repositories:
    maven(https://arti.tw.ee/artifactory/plugins-release)
    MavenLocal(file:/...../.m2/repository/)

**Comment by yevhenii0** [comment]
Hello. Unfortunately the current version requires versions of the libs that are not available in the maven central yet. Though it won't be the case in the near future. We will keep this ticket open until then and will let you know once you can try it out!

**Comment by yevhenii0** [comment]
Hey, you should be able to build the project now! Let me know if something doesn't work for you 😉
